This is the location for references and libraries used by the script.

* The plan is to eventually create output signature files of other formats besides only suricata. Some of the types that we still need to handle are...

whois-registrant-email
domain
domain|ip
x509-fingerprint-sha1
ip-dst
url
filename
sha256
ip-src
md5
ssdeep
filename|md5
filename|sha1
filename|sha256
regkey|value
email-src
sha1
snort
yara
link
hostname
pattern-in-file
threat-actor
email-subject
sha512
mutex
pdb
filename|imphash
http-method
authentihash
imphash
ip-dst|port
sha384
email-dst
filename|sha512
malware-sample
email-attachment
pattern-in-memory
uri
user-agent
other
text
mobile-application-id
attachment
email-src-display-name
regkey
windows-service-name
filename|authentihash
btc
windows-scheduled-task
filename|ssdeep
pattern-in-traffic
named pipe
email-dst-display-name
sha224
email-reply-to
jabber-id
github-username
ip-src|port
bro
email-message-id
size-in-bytes
malware-type
port
